/**
 * Indian dish definitions, expressed as compositions of USDA component foods.
 *
 * Nothing here is an invented macro: every dish is the sum of its parts, scaled to a plated
 * serving weight. Portions vary by kitchen, so the app labels these as estimates.
 *
 * Components are regexes matched against USDA food names (see scripts/build-catalog.mjs).
 */

// Reusable component blocks, in grams.
const C = {
  rice: g => ({ match: '^Rice, white, medium-grain, cooked, unenriched', g }),
  basmati: g => ({ match: '^Rice, white, long-grain, regular, enriched, cooked$', g }),
  atta: g => ({ match: '^Wheat flour, whole-grain', g }),
  maida: g => ({ match: '^Wheat flour, white, all-purpose, enriched, bleached', g }),
  besan: g => ({ match: '^Chickpea flour \\(besan\\)', g }),
  semolina: g => ({ match: '^Semolina, enriched', g }),
  oil: g => ({ match: '^Oil, soybean, salad or cooking$', g }),
  ghee: g => ({ match: '^Ghee, clarified butter', g }),
  butter: g => ({ match: '^Butter, salted', g }),
  onion: g => ({ match: '^Onions, raw', g }),
  tomato: g => ({ match: '^Tomatoes, red, ripe, raw, year round average', g }),
  potato: g => ({ match: '^Potatoes, boiled, cooked in skin, flesh, without salt', g }),
  peas: g => ({ match: '^Peas, green, cooked, boiled, drained, without salt', g }),
  cauliflower: g => ({ match: '^Cauliflower, cooked, boiled, drained, with salt', g }),
  spinach: g => ({ match: '^Spinach, cooked, boiled, drained, without salt', g }),
  eggplant: g => ({ match: '^Eggplant, cooked, boiled, drained, without salt', g }),
  okra: g => ({ match: '^Okra, cooked, boiled, drained, without salt', g }),
  carrot: g => ({ match: '^Carrots, cooked, boiled, drained, without salt', g }),
  cabbage: g => ({ match: '^Cabbage, cooked, boiled, drained, without salt', g }),
  beans: g => ({ match: '^Beans, snap, green, cooked, boiled, drained, without salt', g }),
  gourd: g => ({ match: '^Gourd, white-flowered \\(calabash\\), cooked|^Gourd, dishcloth \\(towelgourd\\), cooked', g }),
  bittergourd: g => ({ match: '^Balsam-pear \\(bitter gourd\\), pods, cooked, boiled, drained, without salt', g }),
  mushroom: g => ({ match: '^Mushrooms, white, cooked, boiled, drained, without salt', g }),
  capsicum: g => ({ match: '^Peppers, sweet, green, cooked, boiled, drained, without salt', g }),
  fenugreek: g => ({ match: '^Spinach, cooked, boiled, drained, without salt', g }), // methi leaves ≈ leafy green
  mustardgreens: g => ({ match: '^Mustard greens, cooked, boiled, drained, without salt', g }),
  radish: g => ({ match: '^Radishes, raw', g }),
  lentil: g => ({ match: '^Lentils, mature seeds, cooked, boiled, without salt', g }),
  chana: g => ({ match: '^Chickpeas \\(garbanzo beans, bengal gram\\), mature seeds, cooked, boiled, without salt', g }),
  rajma: g => ({ match: '^Beans, kidney, red, mature seeds, cooked, boiled, without salt', g }),
  mung: g => ({ match: '^Mung beans, mature seeds, cooked, boiled, without salt', g }),
  soya: g => ({ match: '^Soy protein concentrate, produced by alcohol extraction', g }),
  paneer: g => ({ match: '^Cheese, paneer', g }),
  yogurt: g => ({ match: '^Yogurt, plain, whole milk', g }),
  milk: g => ({ match: '^Milk, whole, 3.25% milkfat, with added vitamin D', g }),
  milkPowder: g => ({ match: '^Milk, dry, whole, without added vitamin D', g }),
  cream: g => ({ match: '^Cream, heavy', g }),
  sugar: g => ({ match: '^Sugars, granulated', g }),
  jaggery: g => ({ match: '^Sugars, brown', g }),
  egg: g => ({ match: '^Egg, whole, cooked, fried', g }),
  eggBoiled: g => ({ match: '^Egg, whole, cooked, hard-boiled', g }),
  chicken: g => ({ match: '^Chicken, broilers or fryers, breast, meat only, cooked, roasted', g }),
  chickenThigh: g => ({ match: '^Chicken, broilers or fryers, thigh, meat only, cooked, roasted', g }),
  mutton: g => ({ match: '^Lamb, shoulder, whole .*separable lean only.*cooked, braised', g }),
  fish: g => ({ match: '^Fish, tilapia, cooked, dry heat', g }),
  prawn: g => ({ match: '^Crustaceans, shrimp, cooked$|^Crustaceans, shrimp, mixed species, cooked, moist heat', g }),
  cashew: g => ({ match: '^Nuts, cashew nuts, raw', g }),
  almond: g => ({ match: '^Nuts, almonds$', g }),
  peanut: g => ({ match: '^Peanuts, all types, raw', g }),
  coconutMilk: g => ({ match: '^Nuts, coconut milk, canned', g }),
  coconut: g => ({ match: '^Nuts, coconut meat, raw', g }),
  tamarind: g => ({ match: '^Tamarinds, raw', g }),
  chutney: g => ({ match: '^Chutney$', g }),
  bread: g => ({ match: '^Bread, white, commercially prepared', g }),
  puffedRice: g => ({ match: '^Cereals ready-to-eat, rice, puffed, fortified', g }),
  noodles: g => ({ match: '^Noodles, egg, cooked, enriched, with added salt', g }),
  tea: g => ({ match: '^Beverages, tea, black, brewed, prepared with tap water', g }),
  coffee: g => ({ match: '^Beverages, coffee, brewed, prepared with tap water', g }),
  lemon: g => ({ match: '^Lemon juice, raw', g }),
  cottage: g => ({ match: '^Cheese, cottage, creamed, large or small curd', g }),
  iceCream: g => ({ match: '^Ice creams, vanilla', g }),
  cornflour: g => ({ match: '^Cornstarch', g }),
}

/** A north-Indian gravy base: onion, tomato and fat. */
const gravy = (onion, tomato, oil) => [C.onion(onion), C.tomato(tomato), C.oil(oil)]

const d = (name, serving_g, components, cuisine = 'Indian') => ({ name, cuisine, serving_g, components })

export const dishes = [
  // ---- Rice ----------------------------------------------------------------
  d('Tawa Pulao', 300, [C.rice(180), C.potato(35), C.peas(25), C.capsicum(20), C.tomato(25), C.onion(20), C.butter(15)]),
  d('Veg Pulao', 300, [C.basmati(190), C.carrot(25), C.peas(25), C.beans(20), C.onion(20), C.ghee(12)]),
  d('Matar Pulao', 300, [C.basmati(200), C.peas(50), C.onion(20), C.ghee(12)]),
  d('Jeera Rice', 250, [C.basmati(210), C.ghee(12), C.onion(10)]),
  d('Ghee Rice', 250, [C.basmati(205), C.ghee(20), C.onion(15), C.cashew(8)]),
  d('Paneer Pulao', 300, [C.basmati(170), C.paneer(60), C.peas(25), C.onion(20), C.ghee(12)]),
  d('Soya Chunk Pulao', 300, [C.basmati(170), C.soya(35), C.onion(25), C.peas(20), C.oil(14)]),
  d('Corn Pulao', 300, [C.basmati(190), C.peas(20), C.onion(20), C.ghee(12)]),
  d('Veg Fried Rice', 300, [C.rice(200), C.cabbage(30), C.carrot(25), C.capsicum(20), C.oil(18)]),
  d('Egg Fried Rice', 300, [C.rice(190), C.egg(55), C.cabbage(25), C.oil(18)]),
  d('Chicken Fried Rice', 320, [C.rice(190), C.chicken(80), C.cabbage(25), C.oil(18)]),
  d('Schezwan Fried Rice', 300, [C.rice(195), C.cabbage(30), C.capsicum(20), C.oil(22), C.chutney(15)]),
  d('Tamarind Rice (Puliyogare)', 250, [C.rice(200), C.tamarind(12), C.peanut(15), C.oil(15)]),
  d('Coconut Rice', 250, [C.rice(200), C.coconut(25), C.oil(12), C.peanut(10)]),
  d('Bisi Bele Bath', 300, [C.rice(150), C.lentil(70), C.carrot(30), C.peas(20), C.ghee(15), C.tamarind(8)]),
  d('Ven Pongal', 280, [C.rice(160), C.mung(70), C.ghee(20), C.cashew(10)]),
  d('Sweet Pongal', 250, [C.rice(140), C.mung(40), C.jaggery(45), C.ghee(20), C.cashew(10)]),
  d('Tehri (Vegetable Rice)', 300, [C.basmati(180), C.potato(40), C.peas(25), C.carrot(20), C.oil(15)]),
  d('Vegetable Biryani (homestyle)', 350, [C.basmati(200), C.potato(40), C.carrot(30), C.peas(25), C.yogurt(30), C.ghee(18), C.onion(25)]),
  d('Paneer Biryani', 350, [C.basmati(190), C.paneer(70), C.yogurt(35), C.ghee(18), C.onion(25)]),
  d('Egg Biryani', 350, [C.basmati(200), C.eggBoiled(55), C.yogurt(30), C.ghee(16), C.onion(25)]),
  d('Mutton Biryani (homestyle)', 350, [C.basmati(180), C.mutton(110), C.yogurt(35), C.ghee(18), C.onion(25)]),

  // ---- Breads --------------------------------------------------------------
  d('Phulka / Plain Roti', 40, [C.atta(35)]),
  d('Tandoori Roti', 60, [C.atta(50), C.oil(3)]),
  d('Butter Naan', 90, [C.maida(60), C.yogurt(12), C.butter(10)]),
  d('Garlic Naan', 90, [C.maida(60), C.yogurt(12), C.butter(8), C.oil(3)]),
  d('Kulcha', 85, [C.maida(60), C.yogurt(12), C.oil(8)]),
  d('Plain Paratha', 70, [C.atta(45), C.ghee(10)]),
  d('Lachha Paratha', 80, [C.atta(50), C.ghee(14)]),
  d('Aloo Paratha', 120, [C.atta(50), C.potato(55), C.ghee(12)]),
  d('Gobi Paratha', 120, [C.atta(50), C.cauliflower(55), C.ghee(12)]),
  d('Paneer Paratha', 120, [C.atta(50), C.paneer(45), C.ghee(12)]),
  d('Methi Paratha', 100, [C.atta(50), C.fenugreek(25), C.ghee(10)]),
  d('Mooli Paratha', 120, [C.atta(50), C.radish(50), C.ghee(12)]),
  d('Missi Roti', 80, [C.atta(30), C.besan(25), C.oil(8)]),
  d('Puri (2 pieces)', 60, [C.atta(35), C.oil(14)]),
  d('Neer Dosa (2 pieces)', 140, [C.rice(110), C.coconut(15), C.oil(6)]),
  d('Akki Roti', 100, [C.rice(80), C.onion(15), C.oil(8)]),
  d('Idiyappam', 150, [C.rice(130), C.coconut(15), C.oil(4)]),
  d('Puttu', 150, [C.rice(120), C.coconut(25)]),

  // ---- Dals ----------------------------------------------------------------
  d('Dal Tadka', 250, [C.lentil(170), ...gravy(25, 35, 14)]),
  d('Dal Fry', 250, [C.lentil(170), ...gravy(30, 30, 16)]),
  d('Moong Dal', 250, [C.mung(170), ...gravy(20, 25, 12)]),
  d('Chana Dal', 250, [C.chana(160), ...gravy(20, 25, 14)]),
  d('Panchmel Dal', 250, [C.lentil(90), C.mung(50), C.chana(35), ...gravy(20, 25, 14)]),
  d('Dal Palak', 250, [C.lentil(140), C.spinach(60), ...gravy(20, 25, 12)]),
  d('Dhaba Dal', 250, [C.lentil(150), C.rajma(25), C.butter(14), ...gravy(20, 30, 8)]),
  d('Kadhi Pakora', 280, [C.yogurt(140), C.besan(35), C.onion(20), C.oil(18)]),

  // ---- Sabzi / curries -----------------------------------------------------
  d('Aloo Matar', 250, [C.potato(120), C.peas(50), ...gravy(20, 40, 14)]),
  d('Jeera Aloo', 200, [C.potato(160), C.oil(14)]),
  d('Dum Aloo', 250, [C.potato(150), C.yogurt(35), ...gravy(20, 35, 16)]),
  d('Bhindi Masala', 220, [C.okra(150), ...gravy(25, 30, 16)]),
  d('Gobi Masala', 250, [C.cauliflower(160), ...gravy(25, 35, 15)]),
  d('Mix Veg Sabzi', 250, [C.carrot(45), C.beans(40), C.cauliflower(45), C.peas(30), C.potato(40), ...gravy(20, 25, 14)]),
  d('Veg Kolhapuri', 260, [C.cauliflower(50), C.carrot(40), C.peas(30), C.capsicum(30), C.coconut(15), ...gravy(25, 40, 18)]),
  d('Paneer Butter Masala', 280, [C.paneer(90), C.tomato(70), C.cream(35), C.butter(18), C.cashew(12), C.onion(20)]),
  d('Kadai Paneer', 280, [C.paneer(95), C.capsicum(40), ...gravy(30, 55, 18)]),
  d('Matar Paneer', 280, [C.paneer(85), C.peas(45), ...gravy(25, 50, 16)]),
  d('Shahi Paneer', 280, [C.paneer(90), C.cream(40), C.cashew(15), ...gravy(25, 45, 15)]),
  d('Chilli Paneer', 250, [C.paneer(110), C.capsicum(40), C.onion(30), C.oil(20), C.cornflour(10)]),
  d('Palak Paneer (homestyle)', 280, [C.paneer(80), C.spinach(140), C.cream(20), ...gravy(20, 20, 14)]),
  d('Mushroom Masala', 250, [C.mushroom(150), ...gravy(25, 40, 16)]),
  d('Soya Chunk Curry', 260, [C.soya(45), ...gravy(30, 50, 16)]),
  d('Egg Curry', 280, [C.eggBoiled(100), ...gravy(30, 55, 16)]),
  d('Egg Bhurji', 180, [C.egg(120), C.onion(30), C.tomato(25), C.oil(12)]),
  d('Lauki Sabzi', 220, [C.gourd(170), ...gravy(20, 30, 12)]),
  d('Karela Sabzi', 200, [C.bittergourd(150), C.onion(25), C.oil(16)]),
  d('Cabbage Sabzi', 200, [C.cabbage(160), C.peas(20), C.oil(12)]),
  d('Methi Aloo', 220, [C.potato(120), C.fenugreek(50), C.oil(15)]),
  d('Sarson Ka Saag', 250, [C.mustardgreens(170), C.spinach(40), C.butter(18), C.onion(20)]),
  d('Avial', 250, [C.carrot(50), C.gourd(50), C.beans(40), C.coconut(30), C.yogurt(40), C.oil(10)]),
  d('Thoran (Cabbage & Coconut)', 200, [C.cabbage(150), C.coconut(30), C.oil(10)]),
  d('Poriyal (Beans)', 200, [C.beans(150), C.coconut(25), C.oil(10)]),
  d('Chole Bhature', 400, [C.chana(150), C.maida(70), C.oil(35), ...gravy(30, 50, 0)]),

  // ---- South Indian tiffin -------------------------------------------------
  d('Masala Dosa', 220, [C.rice(90), C.lentil(35), C.potato(70), C.oil(18)]),
  d('Rava Dosa', 150, [C.semolina(55), C.rice(30), C.oil(20), C.onion(15)]),
  d('Onion Dosa', 180, [C.rice(90), C.lentil(35), C.onion(35), C.oil(15)]),
  d('Set Dosa (2 pieces)', 180, [C.rice(100), C.lentil(40), C.oil(12)]),
  d('Mysore Masala Dosa', 240, [C.rice(90), C.lentil(35), C.potato(70), C.chutney(20), C.oil(22)]),
  d('Rava Idli (2 pieces)', 150, [C.semolina(60), C.yogurt(35), C.oil(8)]),
  d('Poori Masala', 300, [C.atta(50), C.oil(22), C.potato(140), C.onion(25)]),

  // ---- Chaat & street ------------------------------------------------------
  d('Dahi Puri', 160, [C.semolina(30), C.potato(40), C.yogurt(50), C.chutney(20), C.oil(10)]),
  d('Aloo Tikki (2 pieces)', 140, [C.potato(110), C.besan(15), C.oil(18)]),
  d('Ragda Pattice', 300, [C.potato(120), C.chana(120), C.oil(20), C.onion(20), C.chutney(20)]),
  d('Samosa Chaat', 250, [C.maida(40), C.potato(70), C.chana(60), C.yogurt(40), C.oil(22), C.chutney(15)]),
  d('Papdi Chaat', 200, [C.maida(35), C.potato(50), C.yogurt(60), C.chutney(25), C.oil(18)]),
  d('Veg Frankie', 250, [C.maida(60), C.potato(80), C.onion(25), C.oil(18), C.chutney(15)]),
  d('Masala Maggi', 200, [C.noodles(160), C.oil(10), C.onion(20), C.tomato(20)]),
  d('Chinese Bhel', 180, [C.noodles(100), C.cabbage(30), C.capsicum(20), C.oil(20), C.chutney(15)]),
  d('Pav (2 pieces)', 90, [C.bread(85)]),

  // ---- Non-veg -------------------------------------------------------------
  d('Chicken 65', 220, [C.chicken(160), C.cornflour(20), C.yogurt(25), C.oil(25)]),
  d('Chilli Chicken', 250, [C.chicken(160), C.capsicum(35), C.onion(30), C.cornflour(15), C.oil(24)]),
  d('Chicken Curry (homestyle)', 300, [C.chickenThigh(150), ...gravy(35, 60, 18), C.yogurt(25)]),
  d('Mutton Curry', 300, [C.mutton(150), ...gravy(35, 55, 20), C.yogurt(25)]),
  d('Nihari', 300, [C.mutton(150), C.maida(15), ...gravy(30, 40, 25)]),
  d('Haleem', 300, [C.mutton(90), C.lentil(80), C.atta(30), C.ghee(20), C.onion(25)]),
  d('Fish Fry', 180, [C.fish(140), C.semolina(20), C.oil(22)]),
  d('Prawn Curry', 280, [C.prawn(130), C.coconutMilk(50), ...gravy(30, 45, 16)]),
  d('Chicken Kathi Roll', 250, [C.maida(60), C.chicken(90), C.egg(30), C.onion(25), C.oil(14)]),

  // ---- Sweets --------------------------------------------------------------
  d('Rasmalai (2 pieces)', 150, [C.cottage(55), C.milk(70), C.sugar(25), C.almond(6)]),
  d('Sooji Halwa', 150, [C.semolina(45), C.sugar(35), C.ghee(25)]),
  d('Moong Dal Halwa', 150, [C.mung(60), C.sugar(35), C.ghee(30), C.milk(25)]),
  d('Motichoor Laddu (1 piece)', 60, [C.besan(25), C.sugar(25), C.ghee(14)]),
  d('Kaju Katli (2 pieces)', 40, [C.cashew(22), C.sugar(15), C.ghee(4)]),
  d('Milk Peda (2 pieces)', 50, [C.milkPowder(25), C.sugar(18), C.ghee(5)]),
  d('Sandesh (2 pieces)', 80, [C.cottage(50), C.sugar(22)]),
  d('Mysore Pak', 60, [C.besan(20), C.sugar(22), C.ghee(20)]),
  d('Shrikhand', 150, [C.yogurt(110), C.sugar(35), C.almond(6)]),
  d('Basundi', 180, [C.milk(140), C.sugar(30), C.almond(8)]),
  d('Malpua (2 pieces)', 120, [C.maida(35), C.milk(35), C.sugar(30), C.ghee(18)]),
  d('Kulfi', 100, [C.milk(70), C.sugar(20), C.cashew(8)]),
  d('Soan Papdi (2 pieces)', 50, [C.besan(18), C.maida(8), C.sugar(18), C.ghee(8)]),

  // ---- Drinks --------------------------------------------------------------
  d('Masala Chai (1 cup)', 200, [C.tea(120), C.milk(70), C.sugar(10)]),
  d('Black Tea with Sugar', 200, [C.tea(190), C.sugar(8)]),
  d('Filter Coffee', 180, [C.coffee(100), C.milk(70), C.sugar(10)]),
  d('Sweet Lassi', 250, [C.yogurt(180), C.sugar(30), C.milk(30)]),
  d('Salted Lassi / Chaas', 250, [C.yogurt(150), C.milk(90)]),
  d('Badam Milk', 250, [C.milk(200), C.almond(15), C.sugar(20)]),
  d('Nimbu Pani', 250, [C.lemon(25), C.sugar(20)]),
  d('Rose Milk', 250, [C.milk(200), C.sugar(25)]),
  d('Thandai', 250, [C.milk(180), C.almond(15), C.cashew(10), C.sugar(25)]),

  // ---- Snacks --------------------------------------------------------------
  d('Onion Pakora', 120, [C.besan(45), C.onion(45), C.oil(22)]),
  d('Aloo Pakora', 120, [C.besan(40), C.potato(50), C.oil(22)]),
  d('Paneer Pakora', 120, [C.besan(35), C.paneer(50), C.oil(22)]),
  d('Bread Pakora', 140, [C.bread(50), C.besan(30), C.potato(30), C.oil(25)]),
  d('Khandvi', 120, [C.besan(35), C.yogurt(60), C.oil(8), C.coconut(8)]),
  d('Muthiya', 130, [C.besan(35), C.atta(20), C.gourd(45), C.oil(10)]),
  d('Handvo', 150, [C.rice(50), C.chana(35), C.gourd(35), C.yogurt(25), C.oil(14)]),
  d('Chivda / Poha Namkeen', 60, [C.puffedRice(30), C.peanut(15), C.oil(10)]),
  d('Sev / Bhujia', 50, [C.besan(35), C.oil(14)]),
  d('Murukku / Chakli', 60, [C.rice(30), C.besan(15), C.oil(14)]),
  d('Mathri', 60, [C.maida(35), C.oil(18)]),
  d('Peanut Chikki', 50, [C.peanut(28), C.jaggery(22)]),
  d('Roasted Chana', 50, [C.chana(48)]),
  d('Masala Peanuts', 60, [C.peanut(40), C.besan(12), C.oil(10)]),
]

export default dishes
